"""
Generate a PDF with AI-provenance metadata (Creator='Adobe Firefly v3',
Producer claims, SoftwareAgent, etc.). This is the kind of metadata the
watermark-remover sidecar is supposed to strip.
"""
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib.colors import black
import os
from reportlab.pdfbase import pdfdoc

HERE = os.path.dirname(os.path.abspath(__file__))


def make_ai_marked(out_path: str) -> None:
    c = canvas.Canvas(out_path, pagesize=letter)
    # Set AI provenance metadata BEFORE drawing content
    c.setTitle("AI-Generated Cover Letter")
    c.setAuthor("ChatGPT")
    c.setSubject("Generated with GPT-4 model")
    c.setCreator("Adobe Firefly v3.1")
    c.setKeywords(["AI", "synthetic", "gpt-4", "firefly", "ai-generated"])
    # Producer is read-only-ish in ReportLab so we set it via info dict
    if hasattr(c, "_doc") and hasattr(c._doc, "info"):
        # Author/Title/etc already covered above; producer set via canvas._doc.info
        info = c._doc.info
        info.producer = "Adobe Firefly Content Credentials v1.0"

    c.setFont("Helvetica", 12)
    c.setFillColor(black)
    for i, line in enumerate(
        [
            "This document was generated by an AI assistant.",
            "The metadata above contains AI provenance.",
            "",
            "A real human did not write this text.",
            "Use the watermark remover to strip the metadata.",
        ]
    ):
        c.drawString(72, 740 - i * 18, line)
    c.showPage()
    c.save()


if __name__ == "__main__":
    out = os.path.join(HERE, "ai_marked.pdf")
    make_ai_marked(out)
    print("Wrote:", out, os.path.getsize(out), "bytes")
